sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - docker build -t booroogi/react -f Dockerfile.dev .

script: 
  - docker run -e CI=true booroogi/react npm run test -- --coverage

